var Mongoose = require('mongoose');


var formTemplateSchema = Mongoose.Schema({
    name: String,
    inputs: 
        [ 
            { 
                label: String, 
                model: String, 
                autoGenerated: Boolean,
                _id: false 
            }
        ],
    createAt: { type: Date, required: true, default: Date.now }
})

module.exports = Mongoose.model('formTemplate', formTemplateSchema);