var Mongoose = require('mongoose');


var formSchema = Mongoose.Schema({
    name: String,
    inputs: 
        [ 
            { 
                label: String, 
                model: String, 
                autoGenerated: Boolean,
                _id: false 
            }
        ],
    user: { type: Mongoose.Schema.Types.ObjectId, ref: 'User' },
    currentStatus: String,
    actions: 
        {
            _id: false ,
            kind: String,
            by: { type: Mongoose.Schema.Types.ObjectId, ref: 'User' },
            date: Date,
            inputs:  Object
        },
    pastActions: [Object],
    createAt: { type: Date, required: true, default: Date.now }
})

module.exports = Mongoose.model('Form', formSchema);


    // name -- formData.name
    // inputs -- formData.inputs --> loop
//     submittedBy: "54e4bbc6f4b981c0f25c2657", //user
//     Actions [
//         {
//             kinda: // submitted
//             by // user
//             data: Timestamp
//             inputs:
//                 {
//                 firstName: "Travis", 
//                 lastName: "Miller", 
//                 Start Date: "1-12-2015", 
//                 End Date: "1-14-2015"
//                 }
          
//         }
//     ]
//     firstName: "Travis", 
//     lastName: "Miller", 
//     Start Date: "1-12-2015", 
//     End Date: "1-14-2015"
// }
